hospital/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('', include('user.urls')),
    path('registration/',include('registration.urls'),name='registration'),
    path('', include('user.urls')),
    path('medicine/',include('medicine.urls'),name='medicine'),

]

user/urls.py
from django.urls import path, include
from . import views
from django.conf.urls import url

urlpatterns = [
    path('verify_code/', views.verify_code),
    path('register/', views.register, name='register'),
    path('index/', views.index, name='index'),
    path('quit/', views.quit, name='quit'),
    path('role_index/', views.role_index, name='role_index'),
    path('role_jurisdiction/<int:sid>/', views.role_jurisdiction, name='role_jurisdiction'),
    path('user_index/', views.user_index, name='user_index'),
    path('user_deletes/',views.user_deletes, name='user_deletes'),
    path('user_delete/<int:sid>/', views.user_delete, name='user_delete'),
    path('user_editUser/<int:sid>/', views.user_editUser, name='user_editUser'),
    path('password/<int:sid>',views.password,name='password'),
    url('', views.Login, name='login')

]

user/models.py
from django.db import models


# Create your models here.


class Role(models.Model):
    """角色模型类"""
    ORDER_STATUS_CHOICES = (
        (0, '启用'),
        (1, '禁用')
    )
    r_name = models.CharField(max_length=10, verbose_name='角色名称')
    r_status = models.SmallIntegerField(choices=ORDER_STATUS_CHOICES, verbose_name='状态')


class Jurisdiction(models.Model):
    """权限模型类"""
    j_name = models.CharField(max_length=30, verbose_name='权限名称')
    j_jurisdiction = models.ManyToManyField(Role)


class Section(models.Model):
    """科室模型类"""
    name = models.CharField(max_length=5, verbose_name='科室名称')


class User(models.Model):
    """用户模型类"""
    ORDER_STATUS_CHOICES = (
        (0, '启用'),
        (1, '禁用')
    )
    user = models.CharField(max_length=20, verbose_name='账户')
    password = models.CharField(max_length=20, verbose_name='密码')
    name = models.CharField(max_length=20, verbose_name='姓名')
    email = models.EmailField(blank=False, verbose_name='电子邮箱')
    status = models.SmallIntegerField(choices=ORDER_STATUS_CHOICES, default=0, verbose_name='状态')
    role = models.ForeignKey(Role, on_delete=models.CASCADE, verbose_name='角色用户')
    time = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')

templates/role/editRole.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title></title>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'Css/bootstrap.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'Css/bootstrap-responsive.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'Css/style.css' %}" />
    <script type="text/javascript" src="{% static 'Js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'Js/jquery.sorted.js' %}"></script>
    <script type="text/javascript" src="{% static 'Js/bootstrap.js' %}"></script>
    <script type="text/javascript" src="{% static 'Js/ckform.js' %}"></script>
    <script type="text/javascript" src="{% static 'Js/common.js' %}"></script>

    <style type="text/css">
        body {
            padding-bottom: 40px;
        }
        .sidebar-nav {
            padding: 9px 0;
        }

        @media (max-width: 980px) {
            /* Enable use of floated navbar text */
            .navbar-text.pull-right {
                float: none;
                padding-left: 5px;
                padding-right: 5px;
            }
        }


    </style>
</head>
<body>
<form action="{% url 'role_jurisdiction' sid=a.id %}" method="post" class="definewidth m20" >
    {% csrf_token %}
<table class="table table-bordered table-hover definewidth m10">
    <tr>
        <td width="10%" class="tableleft"><font color="red">*</font>角色名称</td>

        <td><input type="text" name="title" value="{{ a.r_name }}"/></td>
    </tr>
    <tr>
        <td class="tableleft"><font color="red">*</font>状态</td>
        <td>
            {% if a.r_status == 0 %}
                <input type="radio" name="status" value="0" checked /> 启用
               <input type="radio" name="status" value="1"  /> 禁用
                {% else %}
                <input type="radio" name="status" value="0" /> 启用
               <input type="radio" name="status" value="1"  checked /> 禁用
            {% endif %}

        </td>
    </tr>
    <tr>
        <td class="tableleft"><font color="red">*</font>权限</td>
        <td>
		<ul>
            {% for foo in b %}
                {% if foo in a.jurisdiction_set.all %}
                 <ul>
                <label class='checkbox inline'><input type='checkbox' checked name='group[]' value='{{ foo.id }}' />{{ foo.j_name }}</label></ul>
</ul>
                    {% else %}
                    <ul>
                <label class='checkbox inline'><input type='checkbox' name='group[]' value='{{ foo.id }}' />{{ foo.j_name }}</label></ul>
</ul>
                {% endif %}

            {% endfor %}

		</td>
    </tr>
    <tr>
        <td class="tableleft"></td>
        <td>
            <button type="submit" class="btn btn-primary" type="button">更新</button> &nbsp;&nbsp;<button type="button" class="btn btn-success" name="backid" id="backid">返回列表</button>
        </td>
    </tr>
</table>
</form>
</body>
</html>
<script>
    $(function () {
        $(':checkbox[name="group[]"]').click(function () {
            $(':checkbox', $(this).closest('li')).prop('checked', this.checked);
        });

		$('#backid').click(function(){
				window.location.href="{% url 'role_index' %}";
		 });

    });
</script>

templates/role/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title></title>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'Css/bootstrap.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'Css/bootstrap-responsive.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'Css/style.css' %}" />
    <script type="text/javascript" src="{% static 'Js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'Js/jquery.sorted.js' %}"></script>
    <script type="text/javascript" src="{% static 'Js/bootstrap.js' %}"></script>
    <script type="text/javascript" src="{% static 'Js/ckform.js' %}"></script>
    <script type="text/javascript" src="{% static 'Js/common.js' %}"></script>

    <style type="text/css">
        body {
            padding-bottom: 40px;
        }
        .sidebar-nav {
            padding: 9px 0;
        }

        @media (max-width: 980px) {
            /* Enable use of floated navbar text */
            .navbar-text.pull-right {
                float: none;
                padding-left: 5px;
                padding-right: 5px;
            }
        }


    </style>
    
     <script type="text/javascript">
     $(function () {
		$('#newNav').click(function(){
				window.location.href="addRole.html";
		 });
    });
	
	
    function checkall(){
			var alls=document.getElementsByName("check");
			var ch=document.getElementById("checkall");
			if(ch.checked){
				for(var i=0;i<alls.length;i++){
					alls[i].checked=true;	
				}	
			}else{
				for(var i=0;i<alls.length;i++){
					alls[i].checked=false;	
				}	
			}
		}
		function delAll(){
			var alls=document.getElementsByName("check");
			var ids=new Array();
			for(var i=0;i<alls.length;i++){
				if(alls[i].checked){
					ids.push(alls[i].value);
				}		
			}
			if(ids.length>0){
				if(confirm("确认删除?")){
					alert("删除成功!");
				}
			}else{
				alert("请选中要删除的项");
			}
		}
    </script>   
    
</head>
<body>
<form class="form-inline definewidth m20" action="index.html" method="get">  
    角色名称：
    <input type="text" name="rolename" id="rolename" class="abc input-default" placeholder="" value="">&nbsp;&nbsp;
    <button type="submit" class="btn btn-primary">查询</button>
</form>
<table class="table table-bordered table-hover definewidth m10" >
    <thead>
    <tr>
    	<th width="5%"><input type="checkbox" id="checkall" onChange="checkall();"></th>
        <th>角色名称</th>
        <th>状态</th>
        <th width="10%">操作</th>
    </tr>
    </thead>
    {% for foo in a %}
        <tr>
         	<td style="vertical-align:middle;">
            <td>{{ foo.r_name }}</td>
            {% if foo.r_status == 0 %}
                <td>启用</td>
                {% else %}
                <td>禁用</td>
            {% endif %}

            <td><a href="{% url 'role_jurisdiction' sid=foo.id %}">编辑</a>&nbsp;&nbsp;&nbsp;<a href="javascript:alert('删除成功！');">删除</a> </td>
        </tr>
    {% endfor %}

	       </table>
 </body>
</html>